### PR TITLE
Simple Dockerfile + fix initialize_native.m

### LINKED ISSUE #59: Docker image for easier deployment on Linux
Provide a Docker image that installs Octave and VOT toolkit.

### PR DESCRIPTION
**Pull request by alantrrs**
Closes #59 

- Fix false error setting up pre-compiled native file on
  initialize_native.m
- Setup test workspace to download trax source
- Compile native files from source & install trax

@lukacu this is how I'm using it right now with Docker. I tested with a native tracker. Let me know if it makes sense, or I can write some instructions and maybe an example of how to use it.

## TODO:
- [ ] Have scripts that initializes the workspace without user input.

### CODE REVIEW

**Comment by lukacu** [comment]
Thank you, I will look at it as soon as possible.

**Comment by lukacu** [comment]
Can you please first resolve the conflicts introduced by the recent updates, then I will merge the changes.

**Comment by alantrrs** [comment]
Ready. BTW, I think we can probably still make this much easier to integrate since you already defined the trax interface to communicate with a tracker. We could have the tracker and the vot-toolkit be on completely different docker containers communicating via the trax interface. I'll develop the idea and submit a PR once I have it.

I'm currently working on an experiment running service, so I'm developing a generic way to do something similar as what I described above.

**Comment by lukacu** [comment]
Great, thanks. Yes, that was also my idea ... to have trackers separated in individual containers, unfortunately for us most academic trackers are written for Matlab on Windows which is not really a Docker-friendly combination.

**Pull request merged**
