### PR TITLE
fix: Cannot find -lrt when initializing native on macOS

### PR DESCRIPTION
**Pull request by cybertk**

### CODE REVIEW

**Comment by lukacu** [comment]
And does it work without this library? I do not have a Mac to test it out.

**Comment by cybertk** [comment]
Yes, I tested on two Macs, latest 10.12.5 and 10.12.1

**Comment by cybertk** [comment]
See this [Topic](https://docs.oracle.com/cd/E36784_01/html/E36873/librt-3lib.html).

It states that, `librt` provides the interfaces specified by the POSIX.1b Realtime Extension in old days. **Now these interfaces moved to libc**

> This library is maintained to provide backward compatibility for both runtime and compilation environments. The shared object is implemented as a filter on libc.so.1. New application development need not specify –lrt.

**Comment by lukacu** [comment]
Great, thanks!

**Comment by cybertk** [comment]
Fine tuned on #124

**Pull request merged**
