### PR TITLE
 tracking result visualization + automatic sequence clustering algorithm

### PR DESCRIPTION
**Pull request by vojirt**
1) visualization of tracking results - added to every workspace
2) sequence clustering algorithm in separate directory

### CODE REVIEW

**Comment by lukacu** [comment]
Apparently there are some conflicts that have to be resolved before merging. Also I have some additional comments:

- I would put clustering directory into the sequence directory.
- All the functions have to be documented.
- Function naming: attr -> attributes (do not abbreviate names in general).
- Some function names are upper case (convert them to underscore separated names).
- run_clustering.m script should be changed to a function. There is no need for a separate clustering_alg directory.
- there is no need for get_aa_region -> we have get_region and region_convert for this.
- I think that cut_patch also already exists as [patch_operation](http://box.vicos.si/vot/toolkit/docs/utilities/patch_operation.html).
- According to current design, all non-interactive visualization functions should be a part of report hierarchy. There is no need to have a separate run_* function.

Most importantly there is a huge amount of new functionality in this commit so it should be well documented.

**Comment by vojirt** [comment]
I addressed all the comments, hopefully it is fine now, since writing doc. and refactoring is painful business :) So check it and let me know.

**Comment by lukacu** [comment]
Great work, it looks much better now. Yes, documentation is painful, but we are trying to maintain some level of code clarity :)

One more thing, is it possible to change pull request to merge against dev branch instead of master? I would prefer to test it first and possibly make some final adjustments ... I am not sure if this is possible, if not then I will do it manually.

**Comment by joelg236** [comment]
:+1: awesome work

https://stackoverflow.com/questions/10081053/how-to-change-the-base-branch-of-a-pull-request

Unless this is outdated, he'll have to make a new pull request for that unfortunately.

**Comment by lukacu** [comment]
Thanks for the tip, if it will not be possible then we can do it manually.

**Comment by lukacu** [comment]
I have manually merged the code to dev branch. Closing request.

**Pull request closed without merging**
